{% set goname = "github.com/hashicorp/packer" %}
{% set version = "1.5.6" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # We must use git here beause the program looks
  # for the git sha&tag to determine its version
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: f63b09580add65974a5188ead84ae5bdedf73cd8621f7a82510956c1dbf6c847

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go install -v .

requirements:
  build:
    - {{ compiler('go') }}
    - {{ compiler('c') }}              # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  requires:
    - m2-bash  # [win]
  commands:
    - bash -c "{{ name|lower }} -v"  # [unix]

about:
  home: https://www.packer.io
  license: MPL-2.0
  summary: Build Automated Machine Images.
  description: |
    HashiCorp Packer is easy to use and automates the creation of any type
    of machine image. It embraces modern configuration management by
    encouraging you to use automated scripts to install and configure the
    software within your Packer-made images
  doc_url: https://www.terraform.io/docs/index.html
  dev_url: https://github.com/hashicorp/terraform.git

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
    - dhirschfeld
