{% set goname = "github.com/hashicorp/packer" %}
{% set version = "1.6.5" %}

{% set name = goname.split('/')[-1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: 983d20903bf62c3f1e424b67d360cbaa835e3022dc2aa35a0c3bb6a5726c2f82

build:
  number: 0
  script:
    - go install -v .

requirements:
  build:
    - {{ compiler('go') }}
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  requires:
    - m2-bash  # [win]
  commands:
    - bash -c "{{ name|lower }} -v"  # [unix]

about:
  home: https://www.packer.io
  license: MPL-2.0
  summary: Build Automated Machine Images.
  description: |
    HashiCorp Packer is easy to use and automates the creation of any type
    of machine image. It embraces modern configuration management by
    encouraging you to use automated scripts to install and configure the
    software within your Packer-made images
  doc_url: https://www.terraform.io/docs/index.html
  dev_url: https://github.com/hashicorp/terraform.git

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
    - dhirschfeld
