{% set goname = "github.com/hashicorp/packer" %}
{% set version = "1.13.1" %}

{% set name = goname.split('/')[-1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: 03d89963c8573ea759c8dd8b2823360fcfa2f9ea1497f88b3b83bac2c8626917

build:
  number: 0
  script:
    - go build -v -ldflags "-w -s -X '{{ goname }}/version.VersionPrerelease='" -o $PREFIX/bin/packer  # [build_platform != target_platform]
    - go install -v -ldflags "-w -s -X '{{ goname }}/version.VersionPrerelease='" .                    # [build_platform == target_platform]
    # Clear cache to avoid excessive file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)                                          # [unix]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('go') }}

test:
  requires:
    - m2-bash  # [win]
  commands:
    - bash -c "{{ name|lower }} -v"  # [unix]

about:
  home: https://www.packer.io
  license: BUSL-1.1
  summary: Build Automated Machine Images.
  description: |
    HashiCorp Packer is easy to use and automates the creation of any type
    of machine image. It embraces modern configuration management by
    encouraging you to use automated scripts to install and configure the
    software within your Packer-made images
  doc_url: https://www.packer.io/docs
  dev_url: https://github.com/hashicorp/packer

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
    - dhirschfeld
    - dbast
