travis:
  secure:
    BINSTAR_TOKEN: XV6LHnceR9FXzhEoBoVFPl0XIPA6xQrliYCLsFoT46j8DoxW7LWIzmB9op13caJmIjLyz5utMh/oxm6/6gwlKmT6lreakhfPBxTqdDzBz6upbe5GPLGvhc6/BuZFuQbzA/t39w41EpIqkdeJvrhd69S+oyh5s8Y2+n52GxcCcUDMcBuvqlS6pcWZpGkmmPBtmPqVX/n9P0UfN0F6DWirigqb+gAzDpJ5Ketau7gu73I7rW+nN3YbI7mZ/5QN1lklBpQ99pjJOhYbmp0DyPmf1ApJG2bwXwffAQx5U4yOkoBMy+AEna+psNJQfu7pV/FJFST+HDxrIJjmGn37JwmbJe/rTInyJCwWfPSJ96/55aj6w2mL55EtXFsW932iAktdcITotTjCT8PVUyD2dlWmFRqkoJsN90qt12lk3wZ3j8xS5txWlqIDlw59M3hIeJoV9jlWYc9bHsPo4TrTZP2aGz5vL4JcI5zO30BvZlCdndW0gJW5WYGvD7++9OyGPUMvy8y/43LWvJb98jMy7ZeJPVMYdzkommS+zw8iSNpfrxv+Q72Z1MSeZYD9VV6RHiAjh8CosCXWbcsO84EnhS/cTNwoY/8KkCGLTI0Ld6lyBLpXRKqPEuRXaXhH0oWqfWrw27TKq7PZNDs58lnHT8f+MlOC0NR6jFpIm3woq+R6EhI=
bot:
  automerge: true
conda_forge_output_validation: true
